name: aax2mp3-easy
version: '1.0'
summary: Easily convert .aax files to .mp3
description:  |
  Easily convert .aax files to .mp3
grade: devel
confinement: devmode

apps:
  aax2mp3-easy:
    command: bash $SNAP/aax2mp3-easy.sh
    plugs:
      - network
      - home
      
parts:
  aax2mp3-easy:
    source: https://github.com/kz6fittycent/aax2mp3-easy
    source-type: git
    plugin: nil
