name: aax2mp3-easy
version: git
summary: Easily convert .aax files to .mp3
description:  |
  Easily convert .aax files to .mp3
grade: stable
confinement: strict
base: core24
source-code: https://github.com/paladini/aax2mp3-easy
issues: https://github.com/kz6fittycent/aax2mp3-easy/issues
contact: https://github.com/kz6fittycent/aax2mp3-easy

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
    
apps:
  aax2mp3-easy:
    command: bin/aax2mp3_easy.sh
    plugs:
      - network
      - home
      
parts:
  aax2mp3-easy:
    source: https://github.com/paladini/aax2mp3-easy
    source-type: git
    plugin: nil
    
  publish:
    plugin: dump
    source: .
    organize:
      "*": /bin/
